apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-tools
  namespace: hw4
spec:
  selector:
    matchLabels:
      app: nettools
  replicas: 3
  template:
    metadata:
      labels:
        app: nettools
    spec:
      containers:
      - name: nginx
        image: dockerhub.timeweb.cloud/nginx:1.25.4
        ports:
        - containerPort: 80
      - name: multitool
        image: dockerhub.timeweb.cloud/wbitt/network-multitool
        ports:
        - containerPort: 8080
        env: 
          - name: HTTP_PORT
            value: "1180"