- name: Install Vector
  hosts: centos-vector
  handlers:
    - name: Start vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: started
  tasks:
    - name: Get package vector
      ansible.builtin.get_url:
        url: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm
        dest: ./vector-{{ vector_version }}-1.x86_64.rpm
    - name: Install vector package
      become: true
      ansible.builtin.yum:
        name: vector-latest-1.x86_64.rpm
      notify: Start vector service
    - name: mkdir vector
      ansible.builtin.file:
        path: /etc/vector
        state: directory
        mode: "0755"
    - name: copy config
      become: true
      ansible.builtin.template:
        src: ./template/jinja2.j2
        dest: /etc/vector/vector.conf
        mode: "0755"
      notify: Start vector service
