- name: Install lighthouse
  hosts: centos-lighthouse
  handlers:
    - name: Reload nginx
      become: true
      command: nginx -s reload
  pre_tasks:
    - name: lighthouse | install git
      become: true
      ansible.builtin.yum:
        name: git
        state: present
  tasks:
    - name: lighthouse | get src git
      become: true
      ansible.builtin.git:
        repo: "{{ lighthouse_git }}"
        dest: "{{ lighthouse_dir }}"
    - name: lighthouse | create dir conf
      ansible.builtin.file:
        path: /etc/nginx/conf.d
        state: directory
    - name: lighthouse | lighthouse conf
      become: true
      ansible.builtin.template:
        src: template/lighthouse.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: "644"
      notify: Reload nginx
